### PR TITLE
Feat/defaultlabelproperty

### PR DESCRIPTION
**Pull request by SteinerPascal**
Please test but I think it should work

### CODE REVIEW

**Comment by SteinerPascal** [comment]
It works as follows: The StartClassGroup and EndClassGroup have a defaultLblVar as a second variable as classmember. If an Action including a Variable is triggered it also does it for the defaultLblVar. 

For the querygeneration it just checks if there is also the defaultLblVar in the Class and if yes then insert it as a triple. 

Btw: the first commit contain some changes i reverted. That's due that i was not happy that i had to call the actionstore state from the query generation. I would like this to remain stateless.

**Comment by tfrancart** [comment]
This works but I need one small adjustement : the added variable MUST be named with the same name as the original variable with "_label" at the end ("Museum_1" and "Museum_1_label"). I am not sure how to do this.

**Comment by SteinerPascal** [comment]
Consider it done. Can i then Merge? this has become a Monster =)

**Comment by tfrancart** [comment]
Yes, you can merge

**Pull request merged**
