### PR TITLE
Fix/eye icon

### PR DESCRIPTION
**Pull request by SteinerPascal**
Fixing the rendering of the SelectViewVar ("eye") Btn on the first startclass. Also including the logic of at least one variable must be selected.

### CODE REVIEW

**Comment by SteinerPascal** [comment]
have a look, test it and merge. or merge right away. Whatever is more to your liking.

**Comment by tfrancart** [comment]
I don't know if this is related to your latest modifications, but:

1. startclassgroups that are at level 2 or below should not be orange if they don't have the eye. No eye, no orange. Eye = orange.
2. there is something wrong in the eye positionning in endclassgroup at level 2, see below:

image

**Comment by SteinerPascal** [comment]
Yes, sorry i actually wanted to delete this branch. I messed a bit up. All the changes are now in feat/defaultlabelproperty. Maybe you test this branch

**Comment by SteinerPascal** [comment]
In this new PR the eye btn location is fixed but the orange color problem still exists. I will fix that in the new branch

**Comment by tfrancart** [comment]
OK ! I will look at feat/defaultlabelproperty then.

**Pull request closed without merging**
