### PR TITLE
TimeWidget fixes

### LINKED ISSUE #78: TimeDate input fields should be larger
image

### PR DESCRIPTION
**Pull request by tfrancart**
Fixes #78 #79 #80 #81 #82

Fixes the time widget overall behavior, as well as improvements in SPARQL query generation

### CODE REVIEW

**Comment by SteinerPascal** [comment]
Can i merge this? I think we should merge our branches as quick as possible

**Comment by tfrancart** [comment]
Yes, please do merge !

**Comment by SteinerPascal** [comment]
Is the SparqlFactory Working?

**Comment by tfrancart** [comment]
Yes, and heavily used in [TimeDatePattern.ts](https://github.com/SteinerPascal/sparnatural-port/pull/84/files#diff-2c7dfb8e07810df59c47f31ed124a0b1bd526e2367d0602d3b05f4b9cd150cea)

**Pull request merged**
